# Generated by Django 4.0.3 on 2022-12-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
