# Generated by Django 4.0.3 on 2022-12-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_remove_sale_purchaser_name_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='vin',
            field=models.CharField(default='', max_length=17),
        ),
    ]
