# Generated by Django 4.0.3 on 2022-12-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_sale_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='sales_rest.automobilevo'),
        ),
    ]
