# Generated by Django 4.0.3 on 2022-12-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_remove_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='vip',
            new_name='status',
        ),
    ]
