# Generated by Django 4.0.3 on 2023-03-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_remove_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='In progress', max_length=100),
        ),
    ]
